import pandas as pd

df = pd.read_csv('log.csv')
print(df.head(20))

df = df.set_index('time')
df = df.sort_index()
print(df.head(20))
print()
print('##########################################################')
df = df.reset_index()
df = df.set_index(['time','user'])
print(df)
print()
print('##########################################################')
df = df.fillna(method='ffill')
print(df.head())
print()
print('##########################################################')
df = pd.DataFrame({'A': [1, 1, 2, 3, 4],
                   'B': [3, 6, 3, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
print(df)
print()
print()
print(df.replace(1,100))
print()
print(df.replace([1,3],[100,300]))
print('##########################################################')
print('##########################################################')
print('##########################################################')
df = pd.read_csv("log.csv")
print(df.head(20))
print('##########################################################')
print()
print(df.replace(to_replace=".*.html$",value="webpage",regex=True))